In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as f

In [2]:
torch.manual_seed(1)

In [3]:
z = torch.FloatTensor([1, 2, 3])

In [4]:
hypothesis = f.softmax(z, dim = 0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [5]:
hypothesis.sum()

tensor(1.)

In [6]:
z = torch.rand(3, 5, requires_grad=True)

In [7]:
hypothesis = f.softmax(z, dim=1)
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)


In [8]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([0, 2, 1])


In [9]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [10]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.4689, grad_fn=<MeanBackward0>)


In [11]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [12]:
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [13]:
y_one_hot = torch.zeros(8, 3)
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
print(y_one_hot)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [14]:
W = torch.zeros((4, 3), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = torch.optim.SGD([W, b], lr = 0.1)

In [15]:
epochs = 2000
for epoch in range(1, epochs + 1):
    hypothesis = f.softmax(x_train.matmul(W) + b, dim = 1)
    
    cost = (y_one_hot * -torch.log(hypothesis)).sum(dim = 1).mean()
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, cost.item()))

Epoch    1/2000 Cost: 1.098612
Epoch    2/2000 Cost: 1.032776
Epoch    3/2000 Cost: 0.985576
Epoch    4/2000 Cost: 0.967064
Epoch    5/2000 Cost: 0.966850
Epoch    6/2000 Cost: 0.985291
Epoch    7/2000 Cost: 1.032398
Epoch    8/2000 Cost: 1.047309
Epoch    9/2000 Cost: 1.091330
Epoch   10/2000 Cost: 1.030258
Epoch   11/2000 Cost: 1.069288
Epoch   12/2000 Cost: 0.996265
Epoch   13/2000 Cost: 1.040883
Epoch   14/2000 Cost: 0.969515
Epoch   15/2000 Cost: 1.016612
Epoch   16/2000 Cost: 0.947535
Epoch   17/2000 Cost: 0.995413
Epoch   18/2000 Cost: 0.929055
Epoch   19/2000 Cost: 0.976886
Epoch   20/2000 Cost: 0.913204
Epoch   21/2000 Cost: 0.960612
Epoch   22/2000 Cost: 0.899367
Epoch   23/2000 Cost: 0.946209
Epoch   24/2000 Cost: 0.887106
Epoch   25/2000 Cost: 0.933357
Epoch   26/2000 Cost: 0.876102
Epoch   27/2000 Cost: 0.921794
Epoch   28/2000 Cost: 0.866122
Epoch   29/2000 Cost: 0.911309
Epoch   30/2000 Cost: 0.856992
Epoch   31/2000 Cost: 0.901738
Epoch   32/2000 Cost: 0.848577
Epoch   

Epoch  312/2000 Cost: 0.586351
Epoch  313/2000 Cost: 0.638263
Epoch  314/2000 Cost: 0.585557
Epoch  315/2000 Cost: 0.637444
Epoch  316/2000 Cost: 0.584767
Epoch  317/2000 Cost: 0.636628
Epoch  318/2000 Cost: 0.583981
Epoch  319/2000 Cost: 0.635815
Epoch  320/2000 Cost: 0.583197
Epoch  321/2000 Cost: 0.635003
Epoch  322/2000 Cost: 0.582417
Epoch  323/2000 Cost: 0.634194
Epoch  324/2000 Cost: 0.581640
Epoch  325/2000 Cost: 0.633388
Epoch  326/2000 Cost: 0.580866
Epoch  327/2000 Cost: 0.632583
Epoch  328/2000 Cost: 0.580096
Epoch  329/2000 Cost: 0.631781
Epoch  330/2000 Cost: 0.579328
Epoch  331/2000 Cost: 0.630981
Epoch  332/2000 Cost: 0.578563
Epoch  333/2000 Cost: 0.630183
Epoch  334/2000 Cost: 0.577802
Epoch  335/2000 Cost: 0.629388
Epoch  336/2000 Cost: 0.577043
Epoch  337/2000 Cost: 0.628594
Epoch  338/2000 Cost: 0.576287
Epoch  339/2000 Cost: 0.627802
Epoch  340/2000 Cost: 0.575534
Epoch  341/2000 Cost: 0.627013
Epoch  342/2000 Cost: 0.574784
Epoch  343/2000 Cost: 0.626225
Epoch  3

Epoch  707/2000 Cost: 0.498285
Epoch  708/2000 Cost: 0.463076
Epoch  709/2000 Cost: 0.497616
Epoch  710/2000 Cost: 0.462537
Epoch  711/2000 Cost: 0.496947
Epoch  712/2000 Cost: 0.461999
Epoch  713/2000 Cost: 0.496279
Epoch  714/2000 Cost: 0.461462
Epoch  715/2000 Cost: 0.495610
Epoch  716/2000 Cost: 0.460924
Epoch  717/2000 Cost: 0.494942
Epoch  718/2000 Cost: 0.460387
Epoch  719/2000 Cost: 0.494273
Epoch  720/2000 Cost: 0.459851
Epoch  721/2000 Cost: 0.493605
Epoch  722/2000 Cost: 0.459314
Epoch  723/2000 Cost: 0.492937
Epoch  724/2000 Cost: 0.458778
Epoch  725/2000 Cost: 0.492269
Epoch  726/2000 Cost: 0.458242
Epoch  727/2000 Cost: 0.491601
Epoch  728/2000 Cost: 0.457707
Epoch  729/2000 Cost: 0.490933
Epoch  730/2000 Cost: 0.457172
Epoch  731/2000 Cost: 0.490265
Epoch  732/2000 Cost: 0.456637
Epoch  733/2000 Cost: 0.489597
Epoch  734/2000 Cost: 0.456102
Epoch  735/2000 Cost: 0.488929
Epoch  736/2000 Cost: 0.455568
Epoch  737/2000 Cost: 0.488262
Epoch  738/2000 Cost: 0.455034
Epoch  7

Epoch 1155/2000 Cost: 0.348456
Epoch 1156/2000 Cost: 0.343382
Epoch 1157/2000 Cost: 0.347800
Epoch 1158/2000 Cost: 0.342830
Epoch 1159/2000 Cost: 0.347144
Epoch 1160/2000 Cost: 0.342279
Epoch 1161/2000 Cost: 0.346490
Epoch 1162/2000 Cost: 0.341728
Epoch 1163/2000 Cost: 0.345837
Epoch 1164/2000 Cost: 0.341176
Epoch 1165/2000 Cost: 0.345184
Epoch 1166/2000 Cost: 0.340626
Epoch 1167/2000 Cost: 0.344533
Epoch 1168/2000 Cost: 0.340074
Epoch 1169/2000 Cost: 0.343882
Epoch 1170/2000 Cost: 0.339524
Epoch 1171/2000 Cost: 0.343232
Epoch 1172/2000 Cost: 0.338973
Epoch 1173/2000 Cost: 0.342584
Epoch 1174/2000 Cost: 0.338422
Epoch 1175/2000 Cost: 0.341936
Epoch 1176/2000 Cost: 0.337872
Epoch 1177/2000 Cost: 0.341290
Epoch 1178/2000 Cost: 0.337322
Epoch 1179/2000 Cost: 0.340645
Epoch 1180/2000 Cost: 0.336772
Epoch 1181/2000 Cost: 0.340001
Epoch 1182/2000 Cost: 0.336223
Epoch 1183/2000 Cost: 0.339358
Epoch 1184/2000 Cost: 0.335674
Epoch 1185/2000 Cost: 0.338717
Epoch 1186/2000 Cost: 0.335125
Epoch 11

Epoch 1495/2000 Cost: 0.285824
Epoch 1496/2000 Cost: 0.285733
Epoch 1497/2000 Cost: 0.285642
Epoch 1498/2000 Cost: 0.285551
Epoch 1499/2000 Cost: 0.285460
Epoch 1500/2000 Cost: 0.285370
Epoch 1501/2000 Cost: 0.285279
Epoch 1502/2000 Cost: 0.285188
Epoch 1503/2000 Cost: 0.285097
Epoch 1504/2000 Cost: 0.285007
Epoch 1505/2000 Cost: 0.284917
Epoch 1506/2000 Cost: 0.284826
Epoch 1507/2000 Cost: 0.284736
Epoch 1508/2000 Cost: 0.284645
Epoch 1509/2000 Cost: 0.284555
Epoch 1510/2000 Cost: 0.284465
Epoch 1511/2000 Cost: 0.284375
Epoch 1512/2000 Cost: 0.284285
Epoch 1513/2000 Cost: 0.284195
Epoch 1514/2000 Cost: 0.284105
Epoch 1515/2000 Cost: 0.284015
Epoch 1516/2000 Cost: 0.283925
Epoch 1517/2000 Cost: 0.283835
Epoch 1518/2000 Cost: 0.283745
Epoch 1519/2000 Cost: 0.283656
Epoch 1520/2000 Cost: 0.283566
Epoch 1521/2000 Cost: 0.283476
Epoch 1522/2000 Cost: 0.283387
Epoch 1523/2000 Cost: 0.283297
Epoch 1524/2000 Cost: 0.283208
Epoch 1525/2000 Cost: 0.283119
Epoch 1526/2000 Cost: 0.283029
Epoch 15

Epoch 1883/2000 Cost: 0.254361
Epoch 1884/2000 Cost: 0.254289
Epoch 1885/2000 Cost: 0.254217
Epoch 1886/2000 Cost: 0.254145
Epoch 1887/2000 Cost: 0.254073
Epoch 1888/2000 Cost: 0.254000
Epoch 1889/2000 Cost: 0.253928
Epoch 1890/2000 Cost: 0.253856
Epoch 1891/2000 Cost: 0.253784
Epoch 1892/2000 Cost: 0.253712
Epoch 1893/2000 Cost: 0.253640
Epoch 1894/2000 Cost: 0.253569
Epoch 1895/2000 Cost: 0.253496
Epoch 1896/2000 Cost: 0.253425
Epoch 1897/2000 Cost: 0.253353
Epoch 1898/2000 Cost: 0.253281
Epoch 1899/2000 Cost: 0.253209
Epoch 1900/2000 Cost: 0.253138
Epoch 1901/2000 Cost: 0.253066
Epoch 1902/2000 Cost: 0.252995
Epoch 1903/2000 Cost: 0.252923
Epoch 1904/2000 Cost: 0.252852
Epoch 1905/2000 Cost: 0.252780
Epoch 1906/2000 Cost: 0.252709
Epoch 1907/2000 Cost: 0.252638
Epoch 1908/2000 Cost: 0.252566
Epoch 1909/2000 Cost: 0.252495
Epoch 1910/2000 Cost: 0.252423
Epoch 1911/2000 Cost: 0.252352
Epoch 1912/2000 Cost: 0.252281
Epoch 1913/2000 Cost: 0.252210
Epoch 1914/2000 Cost: 0.252139
Epoch 19

In [16]:
torch.log(f.softmax(x_train, dim = 1))

tensor([[-1.7437, -0.7437, -1.7437, -1.7437],
        [-1.6265, -2.6265, -0.6265, -1.6265],
        [-1.5797, -3.5797, -1.5797, -0.5797],
        [-1.8697, -4.8697, -0.8697, -0.8697],
        [-6.2415, -0.2415, -2.2415, -2.2415],
        [-5.3314, -4.3314, -1.3314, -0.3314],
        [-6.1009, -1.1009, -1.1009, -1.1009],
        [-7.0994, -1.0994, -1.0994, -1.0994]])

In [17]:
f.log_softmax(x_train, dim = 1)

tensor([[-1.7437, -0.7437, -1.7437, -1.7437],
        [-1.6265, -2.6265, -0.6265, -1.6265],
        [-1.5797, -3.5797, -1.5797, -0.5797],
        [-1.8697, -4.8697, -0.8697, -0.8697],
        [-6.2415, -0.2415, -2.2415, -2.2415],
        [-5.3314, -4.3314, -1.3314, -0.3314],
        [-6.1009, -1.1009, -1.1009, -1.1009],
        [-7.0994, -1.0994, -1.0994, -1.0994]])

In [18]:
(y_one_hot * -torch.log(f.softmax(x_train.matmul(W) + b, dim = 1))).sum(dim = 1).mean()

tensor(0.2461, grad_fn=<MeanBackward0>)

In [19]:
(y_one_hot * -f.log_softmax(x_train.matmul(W) + b, dim = 1)).sum(dim = 1).mean()

tensor(0.2461, grad_fn=<MeanBackward0>)

In [20]:
f.nll_loss(f.log_softmax(x_train.matmul(W) + b, dim = 1), y_train)

tensor(0.2461, grad_fn=<NllLossBackward>)

In [21]:
f.cross_entropy(x_train.matmul(W) + b, y_train)

tensor(0.2461, grad_fn=<NllLossBackward>)

In [22]:
print(hypothesis)
print(W)
print(b)

tensor([[6.4582e-05, 5.0411e-03, 9.9489e-01],
        [1.3823e-02, 2.2173e-01, 7.6445e-01],
        [2.4595e-07, 3.0015e-01, 6.9985e-01],
        [1.7628e-06, 6.8974e-01, 3.1026e-01],
        [2.9599e-01, 6.7674e-01, 2.7270e-02],
        [1.4563e-01, 8.5437e-01, 1.0443e-08],
        [7.4202e-01, 2.5797e-01, 5.5896e-06],
        [8.8598e-01, 1.1402e-01, 1.6200e-07]], grad_fn=<SoftmaxBackward>)
tensor([[-5.1414, -0.2339,  5.3754],
        [-1.0976, -0.6525,  1.7500],
        [ 3.7803, -0.8264, -2.9540],
        [-1.1117,  2.0559, -0.9443]], requires_grad=True)
tensor([1.3724e-06], requires_grad=True)


In [23]:
new_var = torch.FloatTensor([1, 7, 7, 7])
pred = f.softmax(new_var.matmul(W) + b, dim = 0)
print(pred)
print(pred.max(dim = 0)[1])

tensor([8.8603e-01, 1.1397e-01, 1.6141e-07], grad_fn=<SoftmaxBackward>)
tensor(0)


In [24]:
W = torch.zeros((4, 3), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = torch.optim.SGD([W, b], lr = 0.1)

In [25]:
epochs = 2000
for epoch in range(1, epochs + 1):
    z = x_train.matmul(W) + b
    
    cost = f.cross_entropy(z, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, cost.item()))

Epoch    1/2000 Cost: 1.098612
Epoch    2/2000 Cost: 1.032775
Epoch    3/2000 Cost: 0.985576
Epoch    4/2000 Cost: 0.967064
Epoch    5/2000 Cost: 0.966850
Epoch    6/2000 Cost: 0.985291
Epoch    7/2000 Cost: 1.032399
Epoch    8/2000 Cost: 1.047309
Epoch    9/2000 Cost: 1.091330
Epoch   10/2000 Cost: 1.030258
Epoch   11/2000 Cost: 1.069288
Epoch   12/2000 Cost: 0.996265
Epoch   13/2000 Cost: 1.040883
Epoch   14/2000 Cost: 0.969515
Epoch   15/2000 Cost: 1.016612
Epoch   16/2000 Cost: 0.947535
Epoch   17/2000 Cost: 0.995413
Epoch   18/2000 Cost: 0.929055
Epoch   19/2000 Cost: 0.976886
Epoch   20/2000 Cost: 0.913204
Epoch   21/2000 Cost: 0.960612
Epoch   22/2000 Cost: 0.899367
Epoch   23/2000 Cost: 0.946210
Epoch   24/2000 Cost: 0.887106
Epoch   25/2000 Cost: 0.933357
Epoch   26/2000 Cost: 0.876102
Epoch   27/2000 Cost: 0.921794
Epoch   28/2000 Cost: 0.866122
Epoch   29/2000 Cost: 0.911309
Epoch   30/2000 Cost: 0.856992
Epoch   31/2000 Cost: 0.901738
Epoch   32/2000 Cost: 0.848577
Epoch   

Epoch  478/2000 Cost: 0.528788
Epoch  479/2000 Cost: 0.575974
Epoch  480/2000 Cost: 0.528168
Epoch  481/2000 Cost: 0.575269
Epoch  482/2000 Cost: 0.527549
Epoch  483/2000 Cost: 0.574564
Epoch  484/2000 Cost: 0.526930
Epoch  485/2000 Cost: 0.573861
Epoch  486/2000 Cost: 0.526314
Epoch  487/2000 Cost: 0.573158
Epoch  488/2000 Cost: 0.525698
Epoch  489/2000 Cost: 0.572456
Epoch  490/2000 Cost: 0.525083
Epoch  491/2000 Cost: 0.571754
Epoch  492/2000 Cost: 0.524470
Epoch  493/2000 Cost: 0.571053
Epoch  494/2000 Cost: 0.523858
Epoch  495/2000 Cost: 0.570353
Epoch  496/2000 Cost: 0.523247
Epoch  497/2000 Cost: 0.569653
Epoch  498/2000 Cost: 0.522637
Epoch  499/2000 Cost: 0.568954
Epoch  500/2000 Cost: 0.522028
Epoch  501/2000 Cost: 0.568255
Epoch  502/2000 Cost: 0.521421
Epoch  503/2000 Cost: 0.567557
Epoch  504/2000 Cost: 0.520814
Epoch  505/2000 Cost: 0.566860
Epoch  506/2000 Cost: 0.520209
Epoch  507/2000 Cost: 0.566163
Epoch  508/2000 Cost: 0.519604
Epoch  509/2000 Cost: 0.565467
Epoch  5

Epoch  767/2000 Cost: 0.478250
Epoch  768/2000 Cost: 0.447053
Epoch  769/2000 Cost: 0.477583
Epoch  770/2000 Cost: 0.446522
Epoch  771/2000 Cost: 0.476915
Epoch  772/2000 Cost: 0.445992
Epoch  773/2000 Cost: 0.476248
Epoch  774/2000 Cost: 0.445462
Epoch  775/2000 Cost: 0.475581
Epoch  776/2000 Cost: 0.444932
Epoch  777/2000 Cost: 0.474914
Epoch  778/2000 Cost: 0.444403
Epoch  779/2000 Cost: 0.474247
Epoch  780/2000 Cost: 0.443873
Epoch  781/2000 Cost: 0.473580
Epoch  782/2000 Cost: 0.443344
Epoch  783/2000 Cost: 0.472912
Epoch  784/2000 Cost: 0.442815
Epoch  785/2000 Cost: 0.472245
Epoch  786/2000 Cost: 0.442286
Epoch  787/2000 Cost: 0.471578
Epoch  788/2000 Cost: 0.441757
Epoch  789/2000 Cost: 0.470911
Epoch  790/2000 Cost: 0.441229
Epoch  791/2000 Cost: 0.470244
Epoch  792/2000 Cost: 0.440700
Epoch  793/2000 Cost: 0.469577
Epoch  794/2000 Cost: 0.440172
Epoch  795/2000 Cost: 0.468910
Epoch  796/2000 Cost: 0.439644
Epoch  797/2000 Cost: 0.468242
Epoch  798/2000 Cost: 0.439116
Epoch  7

Epoch 1180/2000 Cost: 0.336772
Epoch 1181/2000 Cost: 0.340001
Epoch 1182/2000 Cost: 0.336223
Epoch 1183/2000 Cost: 0.339359
Epoch 1184/2000 Cost: 0.335674
Epoch 1185/2000 Cost: 0.338718
Epoch 1186/2000 Cost: 0.335125
Epoch 1187/2000 Cost: 0.338078
Epoch 1188/2000 Cost: 0.334577
Epoch 1189/2000 Cost: 0.337439
Epoch 1190/2000 Cost: 0.334029
Epoch 1191/2000 Cost: 0.336802
Epoch 1192/2000 Cost: 0.333482
Epoch 1193/2000 Cost: 0.336167
Epoch 1194/2000 Cost: 0.332936
Epoch 1195/2000 Cost: 0.335533
Epoch 1196/2000 Cost: 0.332389
Epoch 1197/2000 Cost: 0.334901
Epoch 1198/2000 Cost: 0.331844
Epoch 1199/2000 Cost: 0.334271
Epoch 1200/2000 Cost: 0.331299
Epoch 1201/2000 Cost: 0.333643
Epoch 1202/2000 Cost: 0.330755
Epoch 1203/2000 Cost: 0.333016
Epoch 1204/2000 Cost: 0.330212
Epoch 1205/2000 Cost: 0.332392
Epoch 1206/2000 Cost: 0.329670
Epoch 1207/2000 Cost: 0.331769
Epoch 1208/2000 Cost: 0.329129
Epoch 1209/2000 Cost: 0.331149
Epoch 1210/2000 Cost: 0.328588
Epoch 1211/2000 Cost: 0.330531
Epoch 12

Epoch 1466/2000 Cost: 0.288490
Epoch 1467/2000 Cost: 0.288397
Epoch 1468/2000 Cost: 0.288304
Epoch 1469/2000 Cost: 0.288212
Epoch 1470/2000 Cost: 0.288119
Epoch 1471/2000 Cost: 0.288027
Epoch 1472/2000 Cost: 0.287934
Epoch 1473/2000 Cost: 0.287842
Epoch 1474/2000 Cost: 0.287749
Epoch 1475/2000 Cost: 0.287657
Epoch 1476/2000 Cost: 0.287565
Epoch 1477/2000 Cost: 0.287473
Epoch 1478/2000 Cost: 0.287381
Epoch 1479/2000 Cost: 0.287289
Epoch 1480/2000 Cost: 0.287197
Epoch 1481/2000 Cost: 0.287105
Epoch 1482/2000 Cost: 0.287013
Epoch 1483/2000 Cost: 0.286921
Epoch 1484/2000 Cost: 0.286830
Epoch 1485/2000 Cost: 0.286738
Epoch 1486/2000 Cost: 0.286646
Epoch 1487/2000 Cost: 0.286555
Epoch 1488/2000 Cost: 0.286463
Epoch 1489/2000 Cost: 0.286372
Epoch 1490/2000 Cost: 0.286280
Epoch 1491/2000 Cost: 0.286189
Epoch 1492/2000 Cost: 0.286098
Epoch 1493/2000 Cost: 0.286006
Epoch 1494/2000 Cost: 0.285915
Epoch 1495/2000 Cost: 0.285824
Epoch 1496/2000 Cost: 0.285733
Epoch 1497/2000 Cost: 0.285642
Epoch 14

Epoch 1884/2000 Cost: 0.254289
Epoch 1885/2000 Cost: 0.254217
Epoch 1886/2000 Cost: 0.254145
Epoch 1887/2000 Cost: 0.254072
Epoch 1888/2000 Cost: 0.254000
Epoch 1889/2000 Cost: 0.253928
Epoch 1890/2000 Cost: 0.253856
Epoch 1891/2000 Cost: 0.253784
Epoch 1892/2000 Cost: 0.253712
Epoch 1893/2000 Cost: 0.253640
Epoch 1894/2000 Cost: 0.253569
Epoch 1895/2000 Cost: 0.253496
Epoch 1896/2000 Cost: 0.253425
Epoch 1897/2000 Cost: 0.253353
Epoch 1898/2000 Cost: 0.253281
Epoch 1899/2000 Cost: 0.253209
Epoch 1900/2000 Cost: 0.253138
Epoch 1901/2000 Cost: 0.253066
Epoch 1902/2000 Cost: 0.252995
Epoch 1903/2000 Cost: 0.252923
Epoch 1904/2000 Cost: 0.252852
Epoch 1905/2000 Cost: 0.252780
Epoch 1906/2000 Cost: 0.252709
Epoch 1907/2000 Cost: 0.252637
Epoch 1908/2000 Cost: 0.252566
Epoch 1909/2000 Cost: 0.252495
Epoch 1910/2000 Cost: 0.252423
Epoch 1911/2000 Cost: 0.252352
Epoch 1912/2000 Cost: 0.252281
Epoch 1913/2000 Cost: 0.252210
Epoch 1914/2000 Cost: 0.252139
Epoch 1915/2000 Cost: 0.252068
Epoch 19

In [26]:
model = nn.Linear(4, 3)

In [27]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

epochs = 2000
for epoch in range(1, epochs + 1):
    prediction = model(x_train)
    
    cost = f.cross_entropy(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, cost.item()))

Epoch    1/2000 Cost: 1.849513
Epoch    2/2000 Cost: 1.298513
Epoch    3/2000 Cost: 1.046181
Epoch    4/2000 Cost: 0.954982
Epoch    5/2000 Cost: 0.929780
Epoch    6/2000 Cost: 0.908864
Epoch    7/2000 Cost: 0.891565
Epoch    8/2000 Cost: 0.877385
Epoch    9/2000 Cost: 0.866827
Epoch   10/2000 Cost: 0.859866
Epoch   11/2000 Cost: 0.859702
Epoch   12/2000 Cost: 0.863017
Epoch   13/2000 Cost: 0.881200
Epoch   14/2000 Cost: 0.887212
Epoch   15/2000 Cost: 0.920919
Epoch   16/2000 Cost: 0.900848
Epoch   17/2000 Cost: 0.935701
Epoch   18/2000 Cost: 0.889786
Epoch   19/2000 Cost: 0.923506
Epoch   20/2000 Cost: 0.871457
Epoch   21/2000 Cost: 0.904911
Epoch   22/2000 Cost: 0.853956
Epoch   23/2000 Cost: 0.887268
Epoch   24/2000 Cost: 0.838455
Epoch   25/2000 Cost: 0.871683
Epoch   26/2000 Cost: 0.824780
Epoch   27/2000 Cost: 0.858027
Epoch   28/2000 Cost: 0.812607
Epoch   29/2000 Cost: 0.845991
Epoch   30/2000 Cost: 0.801657
Epoch   31/2000 Cost: 0.835288
Epoch   32/2000 Cost: 0.791711
Epoch   

Epoch  413/2000 Cost: 0.494249
Epoch  414/2000 Cost: 0.448390
Epoch  415/2000 Cost: 0.493271
Epoch  416/2000 Cost: 0.447575
Epoch  417/2000 Cost: 0.492293
Epoch  418/2000 Cost: 0.446761
Epoch  419/2000 Cost: 0.491317
Epoch  420/2000 Cost: 0.445948
Epoch  421/2000 Cost: 0.490341
Epoch  422/2000 Cost: 0.445138
Epoch  423/2000 Cost: 0.489366
Epoch  424/2000 Cost: 0.444329
Epoch  425/2000 Cost: 0.488393
Epoch  426/2000 Cost: 0.443521
Epoch  427/2000 Cost: 0.487420
Epoch  428/2000 Cost: 0.442715
Epoch  429/2000 Cost: 0.486448
Epoch  430/2000 Cost: 0.441911
Epoch  431/2000 Cost: 0.485477
Epoch  432/2000 Cost: 0.441108
Epoch  433/2000 Cost: 0.484507
Epoch  434/2000 Cost: 0.440307
Epoch  435/2000 Cost: 0.483538
Epoch  436/2000 Cost: 0.439508
Epoch  437/2000 Cost: 0.482569
Epoch  438/2000 Cost: 0.438709
Epoch  439/2000 Cost: 0.481601
Epoch  440/2000 Cost: 0.437913
Epoch  441/2000 Cost: 0.480634
Epoch  442/2000 Cost: 0.437117
Epoch  443/2000 Cost: 0.479668
Epoch  444/2000 Cost: 0.436324
Epoch  4

Epoch  677/2000 Cost: 0.369815
Epoch  678/2000 Cost: 0.349195
Epoch  679/2000 Cost: 0.368890
Epoch  680/2000 Cost: 0.348471
Epoch  681/2000 Cost: 0.367966
Epoch  682/2000 Cost: 0.347747
Epoch  683/2000 Cost: 0.367042
Epoch  684/2000 Cost: 0.347022
Epoch  685/2000 Cost: 0.366118
Epoch  686/2000 Cost: 0.346298
Epoch  687/2000 Cost: 0.365195
Epoch  688/2000 Cost: 0.345574
Epoch  689/2000 Cost: 0.364271
Epoch  690/2000 Cost: 0.344849
Epoch  691/2000 Cost: 0.363348
Epoch  692/2000 Cost: 0.344124
Epoch  693/2000 Cost: 0.362425
Epoch  694/2000 Cost: 0.343400
Epoch  695/2000 Cost: 0.361502
Epoch  696/2000 Cost: 0.342675
Epoch  697/2000 Cost: 0.360579
Epoch  698/2000 Cost: 0.341950
Epoch  699/2000 Cost: 0.359656
Epoch  700/2000 Cost: 0.341225
Epoch  701/2000 Cost: 0.358733
Epoch  702/2000 Cost: 0.340500
Epoch  703/2000 Cost: 0.357811
Epoch  704/2000 Cost: 0.339774
Epoch  705/2000 Cost: 0.356888
Epoch  706/2000 Cost: 0.339049
Epoch  707/2000 Cost: 0.355966
Epoch  708/2000 Cost: 0.338323
Epoch  7

Epoch 1052/2000 Cost: 0.235314
Epoch 1053/2000 Cost: 0.235193
Epoch 1054/2000 Cost: 0.235071
Epoch 1055/2000 Cost: 0.234950
Epoch 1056/2000 Cost: 0.234829
Epoch 1057/2000 Cost: 0.234708
Epoch 1058/2000 Cost: 0.234587
Epoch 1059/2000 Cost: 0.234466
Epoch 1060/2000 Cost: 0.234346
Epoch 1061/2000 Cost: 0.234225
Epoch 1062/2000 Cost: 0.234105
Epoch 1063/2000 Cost: 0.233985
Epoch 1064/2000 Cost: 0.233865
Epoch 1065/2000 Cost: 0.233745
Epoch 1066/2000 Cost: 0.233625
Epoch 1067/2000 Cost: 0.233505
Epoch 1068/2000 Cost: 0.233386
Epoch 1069/2000 Cost: 0.233266
Epoch 1070/2000 Cost: 0.233147
Epoch 1071/2000 Cost: 0.233028
Epoch 1072/2000 Cost: 0.232909
Epoch 1073/2000 Cost: 0.232790
Epoch 1074/2000 Cost: 0.232671
Epoch 1075/2000 Cost: 0.232552
Epoch 1076/2000 Cost: 0.232434
Epoch 1077/2000 Cost: 0.232315
Epoch 1078/2000 Cost: 0.232197
Epoch 1079/2000 Cost: 0.232078
Epoch 1080/2000 Cost: 0.231960
Epoch 1081/2000 Cost: 0.231842
Epoch 1082/2000 Cost: 0.231724
Epoch 1083/2000 Cost: 0.231607
Epoch 10

Epoch 1317/2000 Cost: 0.206912
Epoch 1318/2000 Cost: 0.206818
Epoch 1319/2000 Cost: 0.206723
Epoch 1320/2000 Cost: 0.206629
Epoch 1321/2000 Cost: 0.206534
Epoch 1322/2000 Cost: 0.206440
Epoch 1323/2000 Cost: 0.206346
Epoch 1324/2000 Cost: 0.206252
Epoch 1325/2000 Cost: 0.206158
Epoch 1326/2000 Cost: 0.206064
Epoch 1327/2000 Cost: 0.205970
Epoch 1328/2000 Cost: 0.205876
Epoch 1329/2000 Cost: 0.205783
Epoch 1330/2000 Cost: 0.205689
Epoch 1331/2000 Cost: 0.205596
Epoch 1332/2000 Cost: 0.205502
Epoch 1333/2000 Cost: 0.205409
Epoch 1334/2000 Cost: 0.205316
Epoch 1335/2000 Cost: 0.205222
Epoch 1336/2000 Cost: 0.205129
Epoch 1337/2000 Cost: 0.205036
Epoch 1338/2000 Cost: 0.204943
Epoch 1339/2000 Cost: 0.204850
Epoch 1340/2000 Cost: 0.204757
Epoch 1341/2000 Cost: 0.204665
Epoch 1342/2000 Cost: 0.204572
Epoch 1343/2000 Cost: 0.204480
Epoch 1344/2000 Cost: 0.204387
Epoch 1345/2000 Cost: 0.204295
Epoch 1346/2000 Cost: 0.204203
Epoch 1347/2000 Cost: 0.204110
Epoch 1348/2000 Cost: 0.204018
Epoch 13

Epoch 1690/2000 Cost: 0.176599
Epoch 1691/2000 Cost: 0.176529
Epoch 1692/2000 Cost: 0.176459
Epoch 1693/2000 Cost: 0.176390
Epoch 1694/2000 Cost: 0.176320
Epoch 1695/2000 Cost: 0.176251
Epoch 1696/2000 Cost: 0.176181
Epoch 1697/2000 Cost: 0.176112
Epoch 1698/2000 Cost: 0.176042
Epoch 1699/2000 Cost: 0.175973
Epoch 1700/2000 Cost: 0.175904
Epoch 1701/2000 Cost: 0.175835
Epoch 1702/2000 Cost: 0.175765
Epoch 1703/2000 Cost: 0.175696
Epoch 1704/2000 Cost: 0.175627
Epoch 1705/2000 Cost: 0.175558
Epoch 1706/2000 Cost: 0.175489
Epoch 1707/2000 Cost: 0.175420
Epoch 1708/2000 Cost: 0.175351
Epoch 1709/2000 Cost: 0.175283
Epoch 1710/2000 Cost: 0.175214
Epoch 1711/2000 Cost: 0.175145
Epoch 1712/2000 Cost: 0.175076
Epoch 1713/2000 Cost: 0.175008
Epoch 1714/2000 Cost: 0.174939
Epoch 1715/2000 Cost: 0.174871
Epoch 1716/2000 Cost: 0.174802
Epoch 1717/2000 Cost: 0.174734
Epoch 1718/2000 Cost: 0.174666
Epoch 1719/2000 Cost: 0.174597
Epoch 1720/2000 Cost: 0.174529
Epoch 1721/2000 Cost: 0.174461
Epoch 17

In [28]:
class SoftMaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4, 3)
        
    def forward(self, x):
        return self.linear(x)

In [29]:
model = SoftMaxClassifierModel()

In [30]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

epochs = 2000
for epoch in range(1, epochs + 1):
    prediction = model(x_train)
    
    cost = f.cross_entropy(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, cost.item()))

Epoch    1/2000 Cost: 1.845720
Epoch    2/2000 Cost: 1.460510
Epoch    3/2000 Cost: 1.265032
Epoch    4/2000 Cost: 1.231668
Epoch    5/2000 Cost: 1.214960
Epoch    6/2000 Cost: 1.176336
Epoch    7/2000 Cost: 1.106072
Epoch    8/2000 Cost: 1.103787
Epoch    9/2000 Cost: 1.042308
Epoch   10/2000 Cost: 1.056017
Epoch   11/2000 Cost: 0.989940
Epoch   12/2000 Cost: 1.021716
Epoch   13/2000 Cost: 0.949956
Epoch   14/2000 Cost: 0.994708
Epoch   15/2000 Cost: 0.918371
Epoch   16/2000 Cost: 0.971838
Epoch   17/2000 Cost: 0.892850
Epoch   18/2000 Cost: 0.951761
Epoch   19/2000 Cost: 0.871703
Epoch   20/2000 Cost: 0.933783
Epoch   21/2000 Cost: 0.853773
Epoch   22/2000 Cost: 0.917507
Epoch   23/2000 Cost: 0.838266
Epoch   24/2000 Cost: 0.902678
Epoch   25/2000 Cost: 0.824638
Epoch   26/2000 Cost: 0.889112
Epoch   27/2000 Cost: 0.812502
Epoch   28/2000 Cost: 0.876663
Epoch   29/2000 Cost: 0.801581
Epoch   30/2000 Cost: 0.865215
Epoch   31/2000 Cost: 0.791667
Epoch   32/2000 Cost: 0.854665
Epoch   

Epoch  403/2000 Cost: 0.470905
Epoch  404/2000 Cost: 0.522910
Epoch  405/2000 Cost: 0.470085
Epoch  406/2000 Cost: 0.521953
Epoch  407/2000 Cost: 0.469266
Epoch  408/2000 Cost: 0.520996
Epoch  409/2000 Cost: 0.468449
Epoch  410/2000 Cost: 0.520040
Epoch  411/2000 Cost: 0.467634
Epoch  412/2000 Cost: 0.519085
Epoch  413/2000 Cost: 0.466821
Epoch  414/2000 Cost: 0.518131
Epoch  415/2000 Cost: 0.466009
Epoch  416/2000 Cost: 0.517178
Epoch  417/2000 Cost: 0.465199
Epoch  418/2000 Cost: 0.516226
Epoch  419/2000 Cost: 0.464391
Epoch  420/2000 Cost: 0.515275
Epoch  421/2000 Cost: 0.463585
Epoch  422/2000 Cost: 0.514324
Epoch  423/2000 Cost: 0.462780
Epoch  424/2000 Cost: 0.513374
Epoch  425/2000 Cost: 0.461976
Epoch  426/2000 Cost: 0.512425
Epoch  427/2000 Cost: 0.461175
Epoch  428/2000 Cost: 0.511477
Epoch  429/2000 Cost: 0.460374
Epoch  430/2000 Cost: 0.510530
Epoch  431/2000 Cost: 0.459576
Epoch  432/2000 Cost: 0.509583
Epoch  433/2000 Cost: 0.458779
Epoch  434/2000 Cost: 0.508637
Epoch  4

Epoch  828/2000 Cost: 0.328393
Epoch  829/2000 Cost: 0.315237
Epoch  830/2000 Cost: 0.327489
Epoch  831/2000 Cost: 0.314520
Epoch  832/2000 Cost: 0.326585
Epoch  833/2000 Cost: 0.313803
Epoch  834/2000 Cost: 0.325682
Epoch  835/2000 Cost: 0.313086
Epoch  836/2000 Cost: 0.324779
Epoch  837/2000 Cost: 0.312369
Epoch  838/2000 Cost: 0.323876
Epoch  839/2000 Cost: 0.311651
Epoch  840/2000 Cost: 0.322973
Epoch  841/2000 Cost: 0.310932
Epoch  842/2000 Cost: 0.322071
Epoch  843/2000 Cost: 0.310213
Epoch  844/2000 Cost: 0.321169
Epoch  845/2000 Cost: 0.309494
Epoch  846/2000 Cost: 0.320268
Epoch  847/2000 Cost: 0.308775
Epoch  848/2000 Cost: 0.319366
Epoch  849/2000 Cost: 0.308055
Epoch  850/2000 Cost: 0.318465
Epoch  851/2000 Cost: 0.307335
Epoch  852/2000 Cost: 0.317565
Epoch  853/2000 Cost: 0.306614
Epoch  854/2000 Cost: 0.316664
Epoch  855/2000 Cost: 0.305893
Epoch  856/2000 Cost: 0.315765
Epoch  857/2000 Cost: 0.305172
Epoch  858/2000 Cost: 0.314865
Epoch  859/2000 Cost: 0.304450
Epoch  8

Epoch 1253/2000 Cost: 0.217368
Epoch 1254/2000 Cost: 0.217265
Epoch 1255/2000 Cost: 0.217161
Epoch 1256/2000 Cost: 0.217058
Epoch 1257/2000 Cost: 0.216955
Epoch 1258/2000 Cost: 0.216852
Epoch 1259/2000 Cost: 0.216749
Epoch 1260/2000 Cost: 0.216646
Epoch 1261/2000 Cost: 0.216543
Epoch 1262/2000 Cost: 0.216440
Epoch 1263/2000 Cost: 0.216337
Epoch 1264/2000 Cost: 0.216235
Epoch 1265/2000 Cost: 0.216132
Epoch 1266/2000 Cost: 0.216030
Epoch 1267/2000 Cost: 0.215927
Epoch 1268/2000 Cost: 0.215825
Epoch 1269/2000 Cost: 0.215723
Epoch 1270/2000 Cost: 0.215621
Epoch 1271/2000 Cost: 0.215519
Epoch 1272/2000 Cost: 0.215417
Epoch 1273/2000 Cost: 0.215315
Epoch 1274/2000 Cost: 0.215214
Epoch 1275/2000 Cost: 0.215112
Epoch 1276/2000 Cost: 0.215011
Epoch 1277/2000 Cost: 0.214909
Epoch 1278/2000 Cost: 0.214808
Epoch 1279/2000 Cost: 0.214707
Epoch 1280/2000 Cost: 0.214606
Epoch 1281/2000 Cost: 0.214505
Epoch 1282/2000 Cost: 0.214404
Epoch 1283/2000 Cost: 0.214303
Epoch 1284/2000 Cost: 0.214202
Epoch 12

Epoch 1517/2000 Cost: 0.192960
Epoch 1518/2000 Cost: 0.192877
Epoch 1519/2000 Cost: 0.192795
Epoch 1520/2000 Cost: 0.192713
Epoch 1521/2000 Cost: 0.192630
Epoch 1522/2000 Cost: 0.192548
Epoch 1523/2000 Cost: 0.192466
Epoch 1524/2000 Cost: 0.192384
Epoch 1525/2000 Cost: 0.192302
Epoch 1526/2000 Cost: 0.192220
Epoch 1527/2000 Cost: 0.192138
Epoch 1528/2000 Cost: 0.192056
Epoch 1529/2000 Cost: 0.191975
Epoch 1530/2000 Cost: 0.191893
Epoch 1531/2000 Cost: 0.191811
Epoch 1532/2000 Cost: 0.191730
Epoch 1533/2000 Cost: 0.191648
Epoch 1534/2000 Cost: 0.191567
Epoch 1535/2000 Cost: 0.191486
Epoch 1536/2000 Cost: 0.191404
Epoch 1537/2000 Cost: 0.191323
Epoch 1538/2000 Cost: 0.191242
Epoch 1539/2000 Cost: 0.191161
Epoch 1540/2000 Cost: 0.191080
Epoch 1541/2000 Cost: 0.190999
Epoch 1542/2000 Cost: 0.190918
Epoch 1543/2000 Cost: 0.190837
Epoch 1544/2000 Cost: 0.190756
Epoch 1545/2000 Cost: 0.190676
Epoch 1546/2000 Cost: 0.190595
Epoch 1547/2000 Cost: 0.190515
Epoch 1548/2000 Cost: 0.190434
Epoch 15

Epoch 1892/2000 Cost: 0.166139
Epoch 1893/2000 Cost: 0.166077
Epoch 1894/2000 Cost: 0.166015
Epoch 1895/2000 Cost: 0.165954
Epoch 1896/2000 Cost: 0.165892
Epoch 1897/2000 Cost: 0.165830
Epoch 1898/2000 Cost: 0.165768
Epoch 1899/2000 Cost: 0.165707
Epoch 1900/2000 Cost: 0.165645
Epoch 1901/2000 Cost: 0.165583
Epoch 1902/2000 Cost: 0.165522
Epoch 1903/2000 Cost: 0.165460
Epoch 1904/2000 Cost: 0.165399
Epoch 1905/2000 Cost: 0.165337
Epoch 1906/2000 Cost: 0.165276
Epoch 1907/2000 Cost: 0.165215
Epoch 1908/2000 Cost: 0.165153
Epoch 1909/2000 Cost: 0.165092
Epoch 1910/2000 Cost: 0.165031
Epoch 1911/2000 Cost: 0.164970
Epoch 1912/2000 Cost: 0.164909
Epoch 1913/2000 Cost: 0.164848
Epoch 1914/2000 Cost: 0.164787
Epoch 1915/2000 Cost: 0.164726
Epoch 1916/2000 Cost: 0.164665
Epoch 1917/2000 Cost: 0.164604
Epoch 1918/2000 Cost: 0.164543
Epoch 1919/2000 Cost: 0.164482
Epoch 1920/2000 Cost: 0.164421
Epoch 1921/2000 Cost: 0.164361
Epoch 1922/2000 Cost: 0.164300
Epoch 1923/2000 Cost: 0.164239
Epoch 19